spring.application.name=sentineltrack

spring.datasource.url=jdbc:postgresql://localhost:5432/sentineltrack
spring.datasource.username=sentineltrack
spring.datasource.password=sentineltrack

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

management.endpoints.web.exposure.include=health,info